name: Aktualizuj tylko pytania i zagadnienia w branchu build

on:
  push:
    branches:
      - main

jobs:
  update-zagadnienia-pytania:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch build
      uses: actions/checkout@v4
      with:
        ref: build
        fetch-depth: 0

    - name: Skopiuj pytania i zagadnienia z main do build
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git fetch origin main
        git pull origin build
        rm -rf pytania zagadnienia   
        git checkout origin/main -- pytania zagadnienia   
        git add pytania zagadnienia
        git commit --allow-empty -m "Aktualizacja pytania i zagadnienia z main"
        git push origin build