name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - build  # Tylko branch "build" uruchamia workflow!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Convert Markdown to JSON and generate spis plik√≥w
        run: |
          python md_to_json.py

      - name: List pytania_json to check
        run: |
          ls -l pytania_json

      - name: Copy files for GitHub Pages
        run: |
          mkdir -p public/pytania_json
          cp -r index.html style.css script.js assets/ public/
          cp -r pytania_json/*.json public/pytania_json/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # buildowany katalog
          publish_branch: gh-pages